## Append samples of your project ##
resources:
- infrastructure_v1alpha1_oxidemachine.yaml
- infrastructure_v1alpha1_oxidemachinecluster.yaml
- infrastructure_v1alpha1_oxidemachinetemplate.yaml
- infrastructure_v1alpha1_oxidecluster.yaml
- infrastructure_v1alpha1_oxideclustertemplate.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
