/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	clusterv1 "sigs.k8s.io/cluster-api/api/core/v1beta2"
)

const MachineFinalizer = "oxidemachine.infrastructure.cluster.x-k8s.io"

// OxideMachineSpec defines the desired state of OxideMachine.
type OxideMachineSpec struct {
	// ProviderID is a unique identifier for the Oxide instance for use in correlating across
	// kubernetes resources. Must match provider IDs generated by the Oxide cloud controller
	// manager.
	// https://cluster-api.sigs.k8s.io/reference/glossary#providerid
	ProviderID string `json:"providerID,omitempty"`

	// NCpus is the number of vCPUs to allocate for the instance.
	NCpus int `json:"nCPUs"`
	// Memory is the amount of memory to allocate for the instance, in bytes.
	Memory resource.Quantity `json:"memory"`
	// DiskSize is the size of the boot disk to allocate for the instance, in bytes.
	DiskSize resource.Quantity `json:"diskSize"`

	// ImageID is the ID of the boot disk image.
	ImageID string `json:"imageID"`

	// AntiAffinityGroups is the list of anti-affinity group names or IDs that the Oxide instance
	// should use. Anti-affinity groups should be created outside the operator, else instance
	// creation will fail.
	// https://docs.oxide.computer/guides/deploying-workloads#_affinity_and_anti_affinity
	// +optional
	// +listType=set
	AntiAffinityGroups []string `json:"antiAffinityGroups,omitempty"`

	// SSHPublicKeys is the list of SSH key names or IDs to attach to the Oxide instance. SSH keys
	// should be created outside the operator, else instance creation will fail.
	// https://docs.oxide.computer/guides/user-settings#manage-ssh-keys
	// +optional
	// +listType=set
	SSHPublicKeys []string `json:"sshPublicKeys,omitempty"`

	// IPPool is the Oxide IP pool to use for the instance's external IP. If not set, omit the
	// external IP for the machine. If set, the IP pool must exist.
	// +optional
	IPPool string `json:"ipPool"`
}

type OxideMachineInitializationStatus struct {
	Provisioned *bool `json:"provisioned,omitempty"`
}

// OxideMachineStatus defines the observed state of OxideMachine.
type OxideMachineStatus struct {
	Initialization OxideMachineInitializationStatus `json:"initialization,omitempty"`

	// For Kubernetes API conventions, see:
	// https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties

	// conditions represent the current state of the OxideMachine resource.
	// Each condition has a unique type and reflects the status of a specific aspect of the
	// resource.
	//
	// Standard condition types include:
	// - "Available": the resource is fully functional
	// - "Progressing": the resource is being created or updated
	// - "Degraded": the resource failed to reach or maintain its desired state
	//
	// The status of each condition is one of True, False, or Unknown.
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// addresses contains the associated addresses for the machine.
	// +optional
	Addresses []clusterv1.MachineAddress `json:"addresses,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Cluster",type="string",JSONPath=".metadata.labels.cluster\\.x-k8s\\.io/cluster-name"
// +kubebuilder:printcolumn:name="ProviderID",type="string",JSONPath=".spec.providerID"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Reason",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"

// OxideMachine is the Schema for the oxidemachines API
type OxideMachine struct {
	metav1.TypeMeta `json:",inline"`

	// metadata is a standard object metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// spec defines the desired state of OxideMachine
	// +required
	Spec OxideMachineSpec `json:"spec"`

	// status defines the observed state of OxideMachine
	// +optional
	Status OxideMachineStatus `json:"status,omitzero"`
}

func (m *OxideMachine) GetConditions() []metav1.Condition {
	return m.Status.Conditions
}

func (m *OxideMachine) SetConditions(conditions []metav1.Condition) {
	m.Status.Conditions = conditions
}

// +kubebuilder:object:root=true

// OxideMachineList contains a list of OxideMachine
type OxideMachineList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []OxideMachine `json:"items"`
}

func init() {
	SchemeBuilder.Register(&OxideMachine{}, &OxideMachineList{})
}
