// Code generated by MockGen. DO NOT EDIT.
// Source: oxide.go
//
// Generated by this command:
//
//	mockgen -source=oxide.go -destination=mock/mock_client.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	oxide "github.com/oxidecomputer/oxide.go/oxide"
	gomock "go.uber.org/mock/gomock"
)

// MockOxideClient is a mock of OxideClient interface.
type MockOxideClient struct {
	ctrl     *gomock.Controller
	recorder *MockOxideClientMockRecorder
	isgomock struct{}
}

// MockOxideClientMockRecorder is the mock recorder for MockOxideClient.
type MockOxideClientMockRecorder struct {
	mock *MockOxideClient
}

// NewMockOxideClient creates a new mock instance.
func NewMockOxideClient(ctrl *gomock.Controller) *MockOxideClient {
	mock := &MockOxideClient{ctrl: ctrl}
	mock.recorder = &MockOxideClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOxideClient) EXPECT() *MockOxideClientMockRecorder {
	return m.recorder
}

// DiskDelete mocks base method.
func (m *MockOxideClient) DiskDelete(arg0 context.Context, arg1 oxide.DiskDeleteParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiskDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DiskDelete indicates an expected call of DiskDelete.
func (mr *MockOxideClientMockRecorder) DiskDelete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiskDelete", reflect.TypeOf((*MockOxideClient)(nil).DiskDelete), arg0, arg1)
}

// FloatingIpAttach mocks base method.
func (m *MockOxideClient) FloatingIpAttach(arg0 context.Context, arg1 oxide.FloatingIpAttachParams) (*oxide.FloatingIp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FloatingIpAttach", arg0, arg1)
	ret0, _ := ret[0].(*oxide.FloatingIp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FloatingIpAttach indicates an expected call of FloatingIpAttach.
func (mr *MockOxideClientMockRecorder) FloatingIpAttach(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FloatingIpAttach", reflect.TypeOf((*MockOxideClient)(nil).FloatingIpAttach), arg0, arg1)
}

// FloatingIpCreate mocks base method.
func (m *MockOxideClient) FloatingIpCreate(arg0 context.Context, arg1 oxide.FloatingIpCreateParams) (*oxide.FloatingIp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FloatingIpCreate", arg0, arg1)
	ret0, _ := ret[0].(*oxide.FloatingIp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FloatingIpCreate indicates an expected call of FloatingIpCreate.
func (mr *MockOxideClientMockRecorder) FloatingIpCreate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FloatingIpCreate", reflect.TypeOf((*MockOxideClient)(nil).FloatingIpCreate), arg0, arg1)
}

// FloatingIpDelete mocks base method.
func (m *MockOxideClient) FloatingIpDelete(arg0 context.Context, arg1 oxide.FloatingIpDeleteParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FloatingIpDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// FloatingIpDelete indicates an expected call of FloatingIpDelete.
func (mr *MockOxideClientMockRecorder) FloatingIpDelete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FloatingIpDelete", reflect.TypeOf((*MockOxideClient)(nil).FloatingIpDelete), arg0, arg1)
}

// FloatingIpDetach mocks base method.
func (m *MockOxideClient) FloatingIpDetach(arg0 context.Context, arg1 oxide.FloatingIpDetachParams) (*oxide.FloatingIp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FloatingIpDetach", arg0, arg1)
	ret0, _ := ret[0].(*oxide.FloatingIp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FloatingIpDetach indicates an expected call of FloatingIpDetach.
func (mr *MockOxideClientMockRecorder) FloatingIpDetach(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FloatingIpDetach", reflect.TypeOf((*MockOxideClient)(nil).FloatingIpDetach), arg0, arg1)
}

// FloatingIpView mocks base method.
func (m *MockOxideClient) FloatingIpView(arg0 context.Context, arg1 oxide.FloatingIpViewParams) (*oxide.FloatingIp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FloatingIpView", arg0, arg1)
	ret0, _ := ret[0].(*oxide.FloatingIp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FloatingIpView indicates an expected call of FloatingIpView.
func (mr *MockOxideClientMockRecorder) FloatingIpView(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FloatingIpView", reflect.TypeOf((*MockOxideClient)(nil).FloatingIpView), arg0, arg1)
}

// InstanceCreate mocks base method.
func (m *MockOxideClient) InstanceCreate(arg0 context.Context, arg1 oxide.InstanceCreateParams) (*oxide.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstanceCreate", arg0, arg1)
	ret0, _ := ret[0].(*oxide.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstanceCreate indicates an expected call of InstanceCreate.
func (mr *MockOxideClientMockRecorder) InstanceCreate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstanceCreate", reflect.TypeOf((*MockOxideClient)(nil).InstanceCreate), arg0, arg1)
}

// InstanceDelete mocks base method.
func (m *MockOxideClient) InstanceDelete(arg0 context.Context, arg1 oxide.InstanceDeleteParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstanceDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InstanceDelete indicates an expected call of InstanceDelete.
func (mr *MockOxideClientMockRecorder) InstanceDelete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstanceDelete", reflect.TypeOf((*MockOxideClient)(nil).InstanceDelete), arg0, arg1)
}

// InstanceStart mocks base method.
func (m *MockOxideClient) InstanceStart(arg0 context.Context, arg1 oxide.InstanceStartParams) (*oxide.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstanceStart", arg0, arg1)
	ret0, _ := ret[0].(*oxide.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstanceStart indicates an expected call of InstanceStart.
func (mr *MockOxideClientMockRecorder) InstanceStart(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstanceStart", reflect.TypeOf((*MockOxideClient)(nil).InstanceStart), arg0, arg1)
}

// InstanceStop mocks base method.
func (m *MockOxideClient) InstanceStop(arg0 context.Context, arg1 oxide.InstanceStopParams) (*oxide.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstanceStop", arg0, arg1)
	ret0, _ := ret[0].(*oxide.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstanceStop indicates an expected call of InstanceStop.
func (mr *MockOxideClientMockRecorder) InstanceStop(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstanceStop", reflect.TypeOf((*MockOxideClient)(nil).InstanceStop), arg0, arg1)
}

// InstanceView mocks base method.
func (m *MockOxideClient) InstanceView(arg0 context.Context, arg1 oxide.InstanceViewParams) (*oxide.Instance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstanceView", arg0, arg1)
	ret0, _ := ret[0].(*oxide.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InstanceView indicates an expected call of InstanceView.
func (mr *MockOxideClientMockRecorder) InstanceView(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstanceView", reflect.TypeOf((*MockOxideClient)(nil).InstanceView), arg0, arg1)
}
